version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db

#multicore-insight:
  #image: multicore-insight
  #links:
    #- multicore-node
  #environment:
    #- API_URL=multicore-node
